### PR TITLE
ParseData new function

### PR DESCRIPTION
**Pull request by angelinejohn**
new function to parse data/text and extract some text between the start element and end element

### CODE REVIEW

**Comment by pcud** [comment]
Thank you @angelineflorajohn for the function! I appreciate your willingness to contribute. This seems pretty similar to the "ExtractFromTextBlock" function. Is this distinct enough to add to this repository?

https://github.com/pcud/fm-custom-functions/blob/master/Custom%20Functions/ExtractFromTextBlock.fmfn

**Comment by angelinejohn** [comment]
Thanks for your response @pcud
Both functions are similar, but the ParseData function can get more granular because of the ability to specify the "occurrence" that should be returned, which is not possible with the ExtractTextFromBlock function (if you run the code mentioned below, this difference between the two functions will become clearer). Also, let's say that there is a use case in which we know the starting point or the start string but don't know the end string, so we want the function to return until the end of the text; this is possible with the ParseData function by using the "ENDKEYWORD" as the end string/tag. 


`Let ( [ 
	~text = "remote:Sample File.pdf
size:609,808
JPEG:Secure/6B/E4/DAE10EA5/D254130A/
PDF :Secure/31/B2/55BBA4C5/7DB5_132/
PNGf:Secure/F2/56/65536630/F8278F21/6916_132
";
	~textExtract = ExtractFromTextBlock ( ~text ; "/" ; "/" );
	~parsedData = ParseData ( ~text ; "/" ; "/" ; 2 )
] ; 
	"ExtractTextFromBlock() returns " & ~textExtract & ¶ & "ParseData() returns " & ~parsedData
)`

**Comment by pcud** [comment]
Good points @angelineflorajohn. I like the updated features. Honestly makes me think about adding more like:

- Should it return all matches from the matched text and not just the single occurrence
- What if you're attempting to find the text of "ENDKEYWORD"? 

I'm thinking of updating/creating a new custom function that will solve these two issues. Until than I'll merge your request so both will be available.

**Comment by angelinejohn** [comment]
@pcud, I already have the "ENDKEYWORD" functionality implemented. Let me create another pull request and merge this functionality. 
I like your idea about whether the function should return all matches. I think we should just update "theOccurance" parameter to handle that use case.

**Comment by pcud** [comment]
I generally prefer not using key words like "ENDKEYWORD" when possible. What if someone was specifically looking for that text? The occurrence should be the same.

**Pull request merged**
